spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcommunitydb
    username: testuser
    password: testpass
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: false
    path: /console
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: clientIdTest
            client-secret: clientSecretTest
          facebook:
            client-id: clientIdTest
            client-secret: clientSecretTest
  devtools:
    livereload:
      enabled: true

custom:
  oauth2:
    kakao:
      client-id: clientIdTest
